# Generated by Django 5.1.3 on 2024-11-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateField()),
                ('id_usuario', models.CharField(max_length=11)),
            ],
        ),
    ]
